find_trending_companies:
  description: >
    Encuentre las empresas más populares en las noticias del sector {sector} buscando las últimas noticias. Descubra nuevas empresas que no conocía hasta ahora.
  expected_output: >
    Una lista de empresas en auge en {sector}
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    A partir de una lista de empresas en tendencia, proporcione un análisis detallado de cada empresa en un informe mediante una búsqueda en línea.
  expected_output: >
    Un informe que contiene un análisis detallado de cada empresa.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    Analiza los resultados de la investigación y elige la mejor empresa para invertir.
    Envía una notificación push al usuario con la decisión y una frase que explique los motivos.
    A continuación, responde con un informe detallado sobre por qué has elegido esta empresa y qué empresas no han sido seleccionadas.
  expected_output: >
    La empresa seleccionada y los motivos de su selección; las empresas que no fueron seleccionadas y los motivos de su no selección.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
